# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\neals\Documents\computer science\NEA-project\Great White Shark.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Info_GWS(object):
    def setupUi(self, Information_GWS):
        Information_GWS.setObjectName("Information_GWS")
        Information_GWS.resize(770, 599)
        Information_GWS.setStyleSheet("background-color: rgb(77, 98, 175);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Palatino Linotype\";")
        self.title = QtWidgets.QLabel(Information_GWS)
        self.title.setGeometry(QtCore.QRect(240, 20, 271, 31))
        self.title.setStyleSheet("\n"
"font: 24pt \"Palatino Linotype\";\n"
"text-decoration: underline;\n"
"color: rgb(255, 170, 255);\n"
"")
        self.title.setObjectName("title")
        self.info_box = QtWidgets.QTextBrowser(Information_GWS)
        self.info_box.setGeometry(QtCore.QRect(10, 70, 751, 341))
        self.info_box.setObjectName("info_box")
        self.photo = QtWidgets.QLabel(Information_GWS)
        self.photo.setGeometry(QtCore.QRect(20, 410, 361, 191))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("C:\\Users\\neals\\Documents\\computer science\\NEA-project\\great white.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")

        self.retranslateUi(Information_GWS)
        QtCore.QMetaObject.connectSlotsByName(Information_GWS)

    def retranslateUi(self, Information_GWS):
        _translate = QtCore.QCoreApplication.translate
        Information_GWS.setWindowTitle(_translate("Information_GWS", "Information"))
        self.title.setText(_translate("Information_GWS", "Great White Shark"))
        self.info_box.setHtml(_translate("Information_GWS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Palatino Linotype\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Population</span><span style=\" color:#000000;\">: less then 3,500 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Fun fact: </span><span style=\" font-size:20pt; color:#ffaaff;\">great white sharks existed before dinosaurs</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Dangers: </span><span style=\" color:#000000;\">They are often hunted for their fins,teeth or as a trophy for sport fishing.They are also caught as bycatch and get entangled in meshes that protect beaches</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Diet</span><span style=\" font-size:20pt; font-style:italic; color:#000000;\">: </span><span style=\" color:#000000;\">Once an adult they eat a range of marine animals for example sea lions,seals, dolphines,turtles,other sharks,seabirds and rays</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">General location: </span><span style=\" color:#000000;\">They live in almost all coastal and offshore waters which are between 12 and 24 degreeswith greater concentrations in the U.S, South Africa,Japan, Chile and Australia.One of their densest know populations is found around Dyer Island, South Africa</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Role in ecosystem</span><span style=\" color:#000000;\">:Help to maintain a balanced food web as they are apex predators and limit the abundance of their prey which preserve numbers within the food chain </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Life span</span><span style=\" color:#000000;\">: 70 years or more</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Description</span><span style=\" color:#000000;\">: Can weigh up to 4,500 pounds and are about 21 feet long. This means they are large, bulky fishes and are often described as shaped like a blunt torpedo. Their sharply pointed  conical snout,large pectoral and dorsal fins and strong cresvent shaped tail are some of the key identifiable features along with their white bellies and grey, dark blue or brown patterns on their back</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Fun fact:</span><span style=\" font-size:20pt; color:#ffaaff;\">They can sense blood from up to 3 miles away</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Information_GWS = QtWidgets.QDialog()
    ui = Info_GWS()
    ui.setupUi(Information_GWS)
    Information_GWS.show()
    sys.exit(app.exec_())
