# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\neals\Documents\computer science\NEA-project\Great hammerhead.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Information_HH(object):
    def setupUi(self, Information_HH):
        Information_HH.setObjectName("Information_HH")
        Information_HH.resize(770, 599)
        Information_HH.setStyleSheet("background-color: rgb(77, 98, 175);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Palatino Linotype\";")
        self.title = QtWidgets.QLabel(Information_HH)
        self.title.setGeometry(QtCore.QRect(230, 20, 381, 31))
        self.title.setStyleSheet("\n"
"font: 24pt \"Palatino Linotype\";\n"
"text-decoration: underline;\n"
"color: rgb(255, 170, 255);\n"
"")
        self.title.setObjectName("title")
        self.info_box = QtWidgets.QTextBrowser(Information_HH)
        self.info_box.setGeometry(QtCore.QRect(20, 60, 751, 341))
        self.info_box.setObjectName("info_box")
        self.photo = QtWidgets.QLabel(Information_HH)
        self.photo.setGeometry(QtCore.QRect(20, 410, 361, 191))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("C:\\Users\\neals\\Documents\\computer science\\NEA-project\\Hammerhead-Shark.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")

        self.retranslateUi(Information_HH)
        QtCore.QMetaObject.connectSlotsByName(Information_HH)

    def retranslateUi(self, Information_HH):
        _translate = QtCore.QCoreApplication.translate
        Information_HH.setWindowTitle(_translate("Information_HH", "Information"))
        self.title.setText(_translate("Information_HH", "Great Hammerhead shark"))
        self.info_box.setHtml(_translate("Information_HH", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Palatino Linotype\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Population</span><span style=\" color:#000000;\">: Under 200 and are critically endangered</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Fun fact: </span><span style=\" font-size:20pt; color:#ffaaff;\">Hammerhead sharks can tan from light grey to dark grey</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Dangers: </span><span style=\" color:#000000;\">Hammerhead sharks are particularly vulnerable to being caught in gillnets because of thier unique shape of thier head.They are also targeted mainly for the shark fin trade</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Diet</span><span style=\" font-size:20pt; font-style:italic; color:#000000;\">: </span><span style=\" color:#000000;\">Their diet primarily consists of stringrays, other rays and saktes.But they may also consume other sharks,sea catfish,squid and crustaceans</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Fun fact: </span><span style=\" font-size:20pt; color:#ffaaff;\">they are unaffected by stingray barbs</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">General location: </span><span style=\" color:#000000;\">Found Throughout the Atlantic, Indian and pacific oceans and also in the mediterranean sea.They are most commonly found around the islands of Darwin and Wilf in the Galapagos</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Role in ecosystem</span><span style=\" color:#000000;\">:Help to maintain a balanced food web and ensure the species diversity by controlling the species populations </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Life span</span><span style=\" color:#000000;\">: 20-30 years</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic; color:#ffaaff;\">Description</span><span style=\" color:#000000;\">: Have a stout, dusky brown  and light grey body with a cream coloured underside. They reach a maximum length of 18-20 meters. Their teeth are heavily serrated and triangular. Their exta tall,pointed dorsal fins are easily identifiable along with their hammer shaped heads</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Information_HH = QtWidgets.QDialog()
    ui = Ui_Information_HH()
    ui.setupUi(Information_HH)
    Information_HH.show()
    sys.exit(app.exec_())
