# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NEA-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MonkSeal import Information
from BlueWhale import Info_BW
from Fin import Info_fw
from FurSeal import Info_fur
from Greatwhite import Info_GWS
from HammerH import Info_HH
from Humpback import Info_hump
from SpermWhale import Info_sw
from datetime import datetime


class Ui_mainMenu(object):

    def setupUi(self, mainMenu):
        mainMenu.setObjectName("mainMenu")
        mainMenu.resize(1355, 675)
        mainMenu.setStyleSheet("background-color: rgb(202, 221, 255);")
        self.centralwidget = QtWidgets.QWidget(mainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setGeometry(QtCore.QRect(430, -10, 341, 61))
        self.heading.setStyleSheet("color: rgb(77, 98, 175);\n""font: 24pt \"Palatino Linotype\";\n"
                                   "text-decoration: underline;")
        self.heading.setObjectName("heading")
        self.menu = QtWidgets.QWidget(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 50, 201, 581))
        self.menu.setObjectName("menu")
        self.searchBut = QtWidgets.QPushButton(self.menu)
        self.searchBut.setGeometry(QtCore.QRect(0, 110, 201, 31))
        self.searchBut.setStyleSheet("font: 16pt \"Palatino Linotype\";\n""background-color: rgb(77, 98, 175);\n"
                                     "color: rgb(255, 255, 255);")
        self.searchBut.setObjectName("searchBut")
        self.overlayBut = QtWidgets.QPushButton(self.menu)
        self.overlayBut.setGeometry(QtCore.QRect(0, 190, 201, 31))
        self.overlayBut.setStyleSheet("font: 16pt \"Palatino Linotype\";\n""background-color: rgb(77, 98, 175);\n"
                                      "color: rgb(255, 255, 255);")
        self.overlayBut.setObjectName("overlayBut")
        self.sightingBut = QtWidgets.QPushButton(self.menu)
        self.sightingBut.setGeometry(QtCore.QRect(0, 290, 201, 31))
        self.sightingBut.setStyleSheet("background-color: rgb(77, 98, 175);\n""color: rgb(255, 255, 255);\n"
                                       "font: 16pt \"Palatino Linotype\";")
        self.sightingBut.setObjectName("sightingBut")
        self.graphicsView = QtWidgets.QGraphicsView(self.menu)
        self.graphicsView.setGeometry(QtCore.QRect(200, 60, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.Prediction = QtWidgets.QPushButton(self.menu)
        self.Prediction.setGeometry(QtCore.QRect(0, 390, 201, 31))
        self.Prediction.setStyleSheet("font: 16pt \"Palatino Linotype\";\n"
                                      "background-color: rgb(77, 98, 175);\n"
                                      "color: rgb(255, 255, 255);")
        self.Prediction.setObjectName("Prediction")
        self.Predict_menu = QtWidgets.QWidget(self.menu)
        self.Predict_menu.setGeometry(QtCore.QRect(30, 420, 141, 101))
        self.Predict_menu.setStyleSheet("background-color: rgb(77, 98, 175);")
        self.Predict_menu.setObjectName("Predict_menu")
        self.bw = QtWidgets.QPushButton(self.Predict_menu)
        self.bw.setGeometry(QtCore.QRect(10, 10, 121, 23))
        self.bw.setStyleSheet("color: rgb(77, 98, 175);\n"
                              "font: 8pt \"Palatino Linotype\";\n"
                              "\n"
                              "background-color: rgb(255, 255, 255);\n"
                              "")
        self.bw.setObjectName("bw")
        self.hb = QtWidgets.QPushButton(self.Predict_menu)
        self.hb.setGeometry(QtCore.QRect(10, 40, 121, 23))
        self.hb.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                              "color: rgb(77, 98, 175);\n"
                              "")
        self.hb.setObjectName("hb")
        self.close = QtWidgets.QPushButton(self.Predict_menu)
        self.close.setGeometry(QtCore.QRect(10, 70, 121, 23))
        self.close.setStyleSheet("background-color: rgb(255, 255, 255);\n""color: rgb(77, 98, 175);\n""")
        self.close.setObjectName("close")
        self.key = QtWidgets.QLabel(self.menu)
        self.key.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.key.setStyleSheet("background-color: rgb(246, 208, 255);\n"
                               "font: 10pt \"Palatino Linotype\";\n"
                               "color: rgb(0, 0, 0);\n"
                               "")
        self.key.setObjectName("key")
        self.key_cross = QtWidgets.QLabel(self.menu)
        self.key_cross.setGeometry(QtCore.QRect(20, 30, 31, 31))
        self.key_cross.setStyleSheet("background-color: rgb(246, 208, 255);")
        self.key_cross.setText("")
        self.key_cross.setPixmap(QtGui.QPixmap("cross.png"))
        self.key_cross.setScaledContents(True)
        self.key_cross.setObjectName("key_cross")
        self.imageWorld = QtWidgets.QLabel(self.centralwidget)
        self.imageWorld.setGeometry(QtCore.QRect(200, 70, 1141, 571))
        self.imageWorld.setText("")
        self.imageWorld.setPixmap(QtGui.QPixmap("world_map.png"))
        self.imageWorld.setScaledContents(True)
        self.imageWorld.setObjectName("imageWorld")
        self.zoom = QtWidgets.QPushButton(self.centralwidget)
        self.zoom.setGeometry(QtCore.QRect(1220, 30, 101, 41))
        self.zoom.setStyleSheet("background-color: rgb(77, 98, 175);\n""font: 14pt \"Palatino Linotype\";"
                                "color: rgb(255, 255, 255);")
        self.zoom.setObjectName("zoom")
        self.zoomMenu = QtWidgets.QWidget(self.centralwidget)
        self.zoomMenu.setGeometry(QtCore.QRect(1210, 80, 111, 191))
        self.zoomMenu.setStyleSheet("background-color: rgb(77, 98, 175);")
        self.zoomMenu.setObjectName("zoomMenu")
        self.northA = QtWidgets.QPushButton(self.zoomMenu)
        self.northA.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.northA.setStyleSheet("color: rgb(77, 98, 175);\n""font: 8pt \"Palatino Linotype\";\n""\n"
                                  """background-color: rgb(255, 255, 255);\n""")
        self.northA.setObjectName("northA")
        self.southA = QtWidgets.QPushButton(self.zoomMenu)
        self.southA.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.southA.setStyleSheet("background-color: rgb(255, 255, 255);\n""color: rgb(77, 98, 175);")
        self.southA.setObjectName("southA")
        self.asia = QtWidgets.QPushButton(self.zoomMenu)
        self.asia.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.asia.setStyleSheet("background-color: rgb(255, 255, 255);\n""color: rgb(77, 98, 175);\n""")
        self.asia.setObjectName("asia")
        self.australia = QtWidgets.QPushButton(self.zoomMenu)
        self.australia.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.australia.setStyleSheet("background-color: rgb(255, 255, 255);\n""color: rgb(77, 98, 175);")
        self.australia.setObjectName("australia")
        self.africa = QtWidgets.QPushButton(self.zoomMenu)
        self.africa.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.africa.setStyleSheet("background-color: rgb(255, 255, 255);\n""color: rgb(77, 98, 175);")
        self.africa.setObjectName("africa")
        self.world = QtWidgets.QPushButton(self.zoomMenu)
        self.world.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.world.setStyleSheet("background-color: rgb(255, 255, 255);\n""color: rgb(77, 98, 175);")
        self.world.setObjectName("world")

        self.Main_blueW = QtWidgets.QPushButton(self.centralwidget)
        self.Main_blueW.setGeometry(QtCore.QRect(360, 410, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_blueW.sizePolicy().hasHeightForWidth())
        self.Main_blueW.setSizePolicy(sizePolicy)
        self.Main_blueW.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.Main_blueW.setText("")
        blue_whale = QtGui.QIcon()
        blue_whale.addPixmap(QtGui.QPixmap("Bluewhale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Main_blueW.setIcon(blue_whale)
        self.Main_blueW.setIconSize(QtCore.QSize(60, 60))
        self.Main_blueW.setObjectName("World_blueW")
        self.World_blueW_2 = QtWidgets.QPushButton(self.centralwidget)
        self.World_blueW_2.setGeometry(QtCore.QRect(210, 190, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.World_blueW_2.sizePolicy().hasHeightForWidth())
        self.World_blueW_2.setSizePolicy(sizePolicy)
        self.World_blueW_2.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.World_blueW_2.setText("")
        self.World_blueW_2.setIcon(blue_whale)
        self.World_blueW_2.setIconSize(QtCore.QSize(60, 60))
        self.World_blueW_2.setObjectName("World_blueW_2")
        self.World_blueW_3 = QtWidgets.QPushButton(self.centralwidget)
        self.World_blueW_3.setGeometry(QtCore.QRect(620, 540, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.World_blueW_3.sizePolicy().hasHeightForWidth())
        self.World_blueW_3.setSizePolicy(sizePolicy)
        self.World_blueW_3.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.World_blueW_3.setText("")
        self.World_blueW_3.setIcon(blue_whale)
        self.World_blueW_3.setIconSize(QtCore.QSize(60, 60))
        self.World_blueW_3.setObjectName("World_blueW_3")
        self.Main_Hhead = QtWidgets.QPushButton(self.centralwidget)
        self.Main_Hhead.setGeometry(QtCore.QRect(410, 260, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_Hhead.sizePolicy().hasHeightForWidth())
        self.Main_Hhead.setSizePolicy(sizePolicy)
        self.Main_Hhead.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.Main_Hhead.setText("")
        hammer_head = QtGui.QIcon()
        hammer_head.addPixmap(QtGui.QPixmap("HheadShark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Main_Hhead.setIcon(hammer_head)
        self.Main_Hhead.setIconSize(QtCore.QSize(60, 60))
        self.Main_Hhead.setObjectName("Main_Hhead")
        self.World_Hhead_3 = QtWidgets.QPushButton(self.centralwidget)
        self.World_Hhead_3.setGeometry(QtCore.QRect(1130, 310, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.World_Hhead_3.sizePolicy().hasHeightForWidth())
        self.World_Hhead_3.setSizePolicy(sizePolicy)
        self.World_Hhead_3.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.World_Hhead_3.setText("")
        self.World_Hhead_3.setIcon(hammer_head)
        self.World_Hhead_3.setIconSize(QtCore.QSize(60, 60))
        self.World_Hhead_3.setObjectName("World_Hhead_3")
        self.World_Hhead_2 = QtWidgets.QPushButton(self.centralwidget)
        self.World_Hhead_2.setGeometry(QtCore.QRect(840, 370, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.World_Hhead_2.sizePolicy().hasHeightForWidth())
        self.World_Hhead_2.setSizePolicy(sizePolicy)
        self.World_Hhead_2.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.World_Hhead_2.setText("")
        self.World_Hhead_2.setIcon(hammer_head)
        self.World_Hhead_2.setIconSize(QtCore.QSize(60, 60))
        self.World_Hhead_2.setObjectName("World_Hhead_2")
        self.World_SpermW_2 = QtWidgets.QPushButton(self.centralwidget)
        self.World_SpermW_2.setGeometry(QtCore.QRect(1270, 360, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.World_SpermW_2.sizePolicy().hasHeightForWidth())
        self.World_SpermW_2.setSizePolicy(sizePolicy)
        self.World_SpermW_2.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.World_SpermW_2.setText("")
        sperm_whale = QtGui.QIcon()
        sperm_whale.addPixmap(QtGui.QPixmap("spermWhale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.World_SpermW_2.setIcon(sperm_whale)
        self.World_SpermW_2.setIconSize(QtCore.QSize(60, 60))
        self.World_SpermW_2.setObjectName("World_SpermW_2")
        self.Main_SpermW = QtWidgets.QPushButton(self.centralwidget)
        self.Main_SpermW.setGeometry(QtCore.QRect(540, 460, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_SpermW.sizePolicy().hasHeightForWidth())
        self.Main_SpermW.setSizePolicy(sizePolicy)
        self.Main_SpermW.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.Main_SpermW.setText("")
        self.Main_SpermW.setIcon(sperm_whale)
        self.Main_SpermW.setIconSize(QtCore.QSize(60, 60))
        self.Main_SpermW.setObjectName("Main_SpermW")
        self.Main_monkSeal = QtWidgets.QPushButton(self.centralwidget)
        self.Main_monkSeal.setGeometry(QtCore.QRect(200, 260, 51, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_monkSeal.sizePolicy().hasHeightForWidth())
        self.Main_monkSeal.setSizePolicy(sizePolicy)
        self.Main_monkSeal.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.Main_monkSeal.setText("")
        monk_seal = QtGui.QIcon()
        monk_seal.addPixmap(QtGui.QPixmap("monkSeal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Main_monkSeal.setIcon(monk_seal)
        self.Main_monkSeal.setIconSize(QtCore.QSize(70, 60))
        self.Main_monkSeal.setObjectName("Main_monkSeal")
        self.Main_furSeal = QtWidgets.QPushButton(self.centralwidget)
        self.Main_furSeal.setGeometry(QtCore.QRect(1161, 140, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_furSeal.sizePolicy().hasHeightForWidth())
        self.Main_furSeal.setSizePolicy(sizePolicy)
        self.Main_furSeal.setStyleSheet("background-color: rgb(182, 220, 244);")
        self.Main_furSeal.setText("")
        fur_seal = QtGui.QIcon()
        fur_seal.addPixmap(QtGui.QPixmap("NorthFSeal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Main_furSeal.setIcon(fur_seal)
        self.Main_furSeal.setIconSize(QtCore.QSize(60, 60))
        self.Main_furSeal.setObjectName("Main_furSeal")
        self.World_hump_2 = QtWidgets.QPushButton(self.centralwidget)
        self.World_hump_2.setGeometry(QtCore.QRect(980, 460, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.World_hump_2.sizePolicy().hasHeightForWidth())
        self.World_hump_2.setSizePolicy(sizePolicy)
        self.World_hump_2.setStyleSheet("\n""background-color: rgb(182, 220, 244);")
        self.World_hump_2.setText("")
        humpback = QtGui.QIcon()
        humpback.addPixmap(QtGui.QPixmap("humpbackWhale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.World_hump_2.setIcon(humpback)
        self.World_hump_2.setIconSize(QtCore.QSize(60, 60))
        self.World_hump_2.setObjectName("World_hump_2")
        self.Main_hump = QtWidgets.QPushButton(self.centralwidget)
        self.Main_hump.setGeometry(QtCore.QRect(860, 280, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_hump.sizePolicy().hasHeightForWidth())
        self.Main_hump.setSizePolicy(sizePolicy)
        self.Main_hump.setStyleSheet("\n""background-color: rgb(182, 220, 244);")
        self.Main_hump.setText("")
        self.Main_hump.setIcon(humpback)
        self.Main_hump.setIconSize(QtCore.QSize(60, 60))
        self.Main_hump.setObjectName("Main_hump")
        self.Main_greatW = QtWidgets.QPushButton(self.centralwidget)
        self.Main_greatW.setGeometry(QtCore.QRect(1180, 400, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_greatW.sizePolicy().hasHeightForWidth())
        self.Main_greatW.setSizePolicy(sizePolicy)
        self.Main_greatW.setStyleSheet("border-color: rgb(182, 220, 244);\n"
                                       "background-color: rgb(182, 220, 244);")
        self.Main_greatW.setText("")
        great_white = QtGui.QIcon()
        great_white.addPixmap(QtGui.QPixmap("GreatWshark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Main_greatW.setIcon(great_white)
        self.Main_greatW.setIconSize(QtCore.QSize(60, 60))
        self.Main_greatW.setObjectName("Main_greatW")
        self.World_greatW_3 = QtWidgets.QPushButton(self.centralwidget)
        self.World_greatW_3.setGeometry(QtCore.QRect(1120, 190, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.World_greatW_3.sizePolicy().hasHeightForWidth())
        self.World_greatW_3.setSizePolicy(sizePolicy)
        self.World_greatW_3.setStyleSheet("border-color: rgb(182, 220, 244);\n""background-color: rgb(182, 220, 244);")
        self.World_greatW_3.setText("")
        self.World_greatW_3.setIcon(great_white)
        self.World_greatW_3.setIconSize(QtCore.QSize(60, 60))
        self.World_greatW_3.setObjectName("World_greatW_3")
        self.World_greatW_2 = QtWidgets.QPushButton(self.centralwidget)
        self.World_greatW_2.setGeometry(QtCore.QRect(710, 470, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.World_greatW_2.sizePolicy().hasHeightForWidth())
        self.World_greatW_2.setSizePolicy(sizePolicy)
        self.World_greatW_2.setStyleSheet("border-color: rgb(182, 220, 244);\n"
                                          "background-color: rgb(182, 220, 244);")
        self.World_greatW_2.setText("")
        self.World_greatW_2.setIcon(great_white)
        self.World_greatW_2.setIconSize(QtCore.QSize(60, 60))
        self.World_greatW_2.setObjectName("World_greatW_2")
        self.NA_blueW = QtWidgets.QLabel(self.centralwidget)
        self.NA_blueW.setGeometry(QtCore.QRect(470, 410, 61, 31))
        self.NA_blueW.setStyleSheet("\n"
                                    "background-color: rgb(200, 235, 255);")
        self.NA_blueW.setText("")
        self.NA_blueW.setPixmap(QtGui.QPixmap("Bluewhale.png"))
        self.NA_blueW.setScaledContents(True)
        self.NA_blueW.setObjectName("NA_blueW")
        self.NA_blueW_3 = QtWidgets.QLabel(self.centralwidget)
        self.NA_blueW_3.setGeometry(QtCore.QRect(1080, 290, 41, 31))
        self.NA_blueW_3.setStyleSheet("\n"
                                      "background-color: rgb(200, 235, 255);")
        self.NA_blueW_3.setText("")
        self.NA_blueW_3.setPixmap(QtGui.QPixmap("Bluewhale.png"))
        self.NA_blueW_3.setScaledContents(True)
        self.NA_blueW_3.setObjectName("NA_blueW_3")
        self.NA_blueW_4 = QtWidgets.QLabel(self.centralwidget)
        self.NA_blueW_4.setGeometry(QtCore.QRect(1120, 460, 51, 31))
        self.NA_blueW_4.setStyleSheet("\n"
                                      "background-color: rgb(200, 235, 255);")
        self.NA_blueW_4.setText("")
        self.NA_blueW_4.setPixmap(QtGui.QPixmap("Bluewhale.png"))
        self.NA_blueW_4.setScaledContents(True)
        self.NA_blueW_4.setObjectName("NA_blueW_4")
        self.NA_SpermW = QtWidgets.QLabel(self.centralwidget)
        self.NA_SpermW.setGeometry(QtCore.QRect(880, 480, 61, 51))
        self.NA_SpermW.setStyleSheet("background-color: rgb(200, 235, 255);")
        self.NA_SpermW.setText("")
        self.NA_SpermW.setPixmap(QtGui.QPixmap("spermWhale.png"))
        self.NA_SpermW.setScaledContents(True)
        self.NA_SpermW.setObjectName("NA_SpermW")
        self.Main_finw = QtWidgets.QPushButton(self.centralwidget)
        self.Main_finw.setGeometry(QtCore.QRect(500, 160, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_finw.sizePolicy().hasHeightForWidth())
        self.Main_finw.setSizePolicy(sizePolicy)
        self.Main_finw.setStyleSheet("border-color: rgb(182, 220, 244);\n"
                                     "background-color: rgb(182, 220, 244);")
        self.Main_finw.setText("")
        fin_whale = QtGui.QIcon()
        fin_whale.addPixmap(QtGui.QPixmap("finWhale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Main_finw.setIcon(fin_whale)
        self.Main_finw.setIconSize(QtCore.QSize(60, 60))
        self.Main_finw.setObjectName("Main_finw")
        self.NA_finW = QtWidgets.QLabel(self.centralwidget)
        self.NA_finW.setGeometry(QtCore.QRect(380, 220, 51, 31))
        self.NA_finW.setStyleSheet("background-color: rgb(200, 235, 255);")
        self.NA_finW.setText("")
        self.NA_finW.setPixmap(QtGui.QPixmap("finWhale.png"))
        self.NA_finW.setScaledContents(True)
        self.NA_finW.setObjectName("NA_finW")
        self.NA_humpW = QtWidgets.QLabel(self.centralwidget)
        self.NA_humpW.setGeometry(QtCore.QRect(450, 280, 51, 41))
        self.NA_humpW.setStyleSheet("background-color: rgb(200, 235, 255);")
        self.NA_humpW.setText("")
        self.NA_humpW.setPixmap(QtGui.QPixmap("humpbackWhale.png"))
        self.NA_humpW.setScaledContents(True)
        self.NA_humpW.setObjectName("NA_humpW")
        self.NA_greatwS = QtWidgets.QLabel(self.centralwidget)
        self.NA_greatwS.setGeometry(QtCore.QRect(1130, 360, 71, 31))
        self.NA_greatwS.setStyleSheet("background-color: rgb(200, 235, 255);")
        self.NA_greatwS.setText("")
        self.NA_greatwS.setPixmap(QtGui.QPixmap("GreatWshark.png"))
        self.NA_greatwS.setScaledContents(True)
        self.NA_greatwS.setObjectName("NA_greatwS")
        self.SA_greatwS = QtWidgets.QLabel(self.centralwidget)
        self.SA_greatwS.setGeometry(QtCore.QRect(930, 540, 71, 31))
        self.SA_greatwS.setStyleSheet("background-color: rgb(200, 235, 255);")
        self.SA_greatwS.setText("")
        self.SA_greatwS.setPixmap(QtGui.QPixmap("GreatWshark.png"))
        self.SA_greatwS.setScaledContents(True)
        self.SA_greatwS.setObjectName("SA_greatwS")
        self.SA_spermW = QtWidgets.QPushButton(self.centralwidget)
        self.SA_spermW.setGeometry(QtCore.QRect(1110, 410, 61, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SA_spermW.sizePolicy().hasHeightForWidth())
        self.SA_spermW.setSizePolicy(sizePolicy)
        self.SA_spermW.setStyleSheet("\n""background-color: rgb(200, 235, 255);\n""")
        self.SA_spermW.setText("")
        self.SA_spermW.setIcon(sperm_whale)
        self.SA_spermW.setIconSize(QtCore.QSize(60, 60))
        self.SA_spermW.setObjectName("SA_spermW")
        self.AS_SpermW = QtWidgets.QLabel(self.centralwidget)
        self.AS_SpermW.setGeometry(QtCore.QRect(590, 480, 61, 51))
        self.AS_SpermW.setStyleSheet("background-color: rgb(218, 240, 253);")
        self.AS_SpermW.setText("")
        self.AS_SpermW.setPixmap(QtGui.QPixmap("spermWhale.png"))
        self.AS_SpermW.setScaledContents(True)
        self.AS_SpermW.setObjectName("AS_SpermW")
        self.AS_greatwS = QtWidgets.QLabel(self.centralwidget)
        self.AS_greatwS.setGeometry(QtCore.QRect(980, 360, 71, 31))
        self.AS_greatwS.setStyleSheet("background-color: rgb(218, 240, 253);")
        self.AS_greatwS.setText("")
        self.AS_greatwS.setPixmap(QtGui.QPixmap("GreatWshark.png"))
        self.AS_greatwS.setScaledContents(True)
        self.AS_greatwS.setObjectName("AS_greatwS")
        self.AS_greatwS_2 = QtWidgets.QLabel(self.centralwidget)
        self.AS_greatwS_2.setGeometry(QtCore.QRect(1020, 420, 71, 31))
        self.AS_greatwS_2.setStyleSheet("background-color: rgb(218, 240, 253);")
        self.AS_greatwS_2.setText("")
        self.AS_greatwS_2.setPixmap(QtGui.QPixmap("GreatWshark.png"))
        self.AS_greatwS_2.setScaledContents(True)
        self.AS_greatwS_2.setObjectName("AS_greatwS_2")
        self.AS_headS = QtWidgets.QLabel(self.centralwidget)
        self.AS_headS.setGeometry(QtCore.QRect(920, 420, 71, 41))
        self.AS_headS.setStyleSheet("background-color: rgb(218, 240, 253);")
        self.AS_headS.setText("")
        self.AS_headS.setPixmap(QtGui.QPixmap("HheadShark.png"))
        self.AS_headS.setScaledContents(True)
        self.AS_headS.setObjectName("AS_headS")
        self.AS_headS_2 = QtWidgets.QLabel(self.centralwidget)
        self.AS_headS_2.setGeometry(QtCore.QRect(550, 430, 71, 41))
        self.AS_headS_2.setStyleSheet("background-color: rgb(218, 240, 253);")
        self.AS_headS_2.setText("")
        self.AS_headS_2.setPixmap(QtGui.QPixmap("HheadShark.png"))
        self.AS_headS_2.setScaledContents(True)
        self.AS_headS_2.setObjectName("AS_headS_2")
        self.AUS_headS = QtWidgets.QLabel(self.centralwidget)
        self.AUS_headS.setGeometry(QtCore.QRect(780, 410, 71, 41))
        self.AUS_headS.setStyleSheet("background-color: rgb(200, 234, 251);")
        self.AUS_headS.setText("")
        self.AUS_headS.setPixmap(QtGui.QPixmap("HheadShark.png"))
        self.AUS_headS.setScaledContents(True)
        self.AUS_headS.setObjectName("AUS_headS")
        self.AUS_greatwS = QtWidgets.QLabel(self.centralwidget)
        self.AUS_greatwS.setGeometry(QtCore.QRect(640, 460, 71, 31))
        self.AUS_greatwS.setStyleSheet("background-color: rgb(200, 234, 251);")
        self.AUS_greatwS.setText("")
        self.AUS_greatwS.setPixmap(QtGui.QPixmap("../../../../../.designer/GreatWshark.png"))
        self.AUS_greatwS.setScaledContents(True)
        self.AUS_greatwS.setObjectName("AUS_greatwS")
        self.AUS_greatwS_2 = QtWidgets.QLabel(self.centralwidget)
        self.AUS_greatwS_2.setGeometry(QtCore.QRect(610, 390, 71, 31))
        self.AUS_greatwS_2.setStyleSheet("background-color: rgb(200, 234, 251);")
        self.AUS_greatwS_2.setText("")
        self.AUS_greatwS_2.setPixmap(QtGui.QPixmap("GreatWshark.png"))
        self.AUS_greatwS_2.setScaledContents(True)
        self.AUS_greatwS_2.setObjectName("AUS_greatwS_2")
        self.AUS_SpermW = QtWidgets.QLabel(self.centralwidget)
        self.AUS_SpermW.setGeometry(QtCore.QRect(510, 220, 61, 51))
        self.AUS_SpermW.setStyleSheet("background-color: rgb(200, 234, 251);")
        self.AUS_SpermW.setText("")
        self.AUS_SpermW.setPixmap(QtGui.QPixmap("spermWhale.png"))
        self.AUS_SpermW.setScaledContents(True)
        self.AUS_SpermW.setObjectName("AUS_SpermW")
        self.AUS_SpermW_2 = QtWidgets.QLabel(self.centralwidget)
        self.AUS_SpermW_2.setGeometry(QtCore.QRect(330, 320, 61, 51))
        self.AUS_SpermW_2.setStyleSheet("background-color: rgb(200, 234, 251);")
        self.AUS_SpermW_2.setText("")
        self.AUS_SpermW_2.setPixmap(QtGui.QPixmap("spermWhale.png"))
        self.AUS_SpermW_2.setScaledContents(True)
        self.AUS_SpermW_2.setObjectName("AUS_SpermW_2")
        self.AUS_humpW = QtWidgets.QLabel(self.centralwidget)
        self.AUS_humpW.setGeometry(QtCore.QRect(280, 340, 51, 41))
        self.AUS_humpW.setStyleSheet("background-color: rgb(200, 235, 255);")
        self.AUS_humpW.setText("")
        self.AUS_humpW.setPixmap(QtGui.QPixmap("humpbackWhale.png"))
        self.AUS_humpW.setScaledContents(True)
        self.AUS_humpW.setObjectName("AUS_humpW")
        self.AUS_humpW_2 = QtWidgets.QLabel(self.centralwidget)
        self.AUS_humpW_2.setGeometry(QtCore.QRect(800, 280, 51, 41))
        self.AUS_humpW_2.setStyleSheet("background-color: rgb(200, 235, 255);")
        self.AUS_humpW_2.setText("")
        self.AUS_humpW_2.setPixmap(QtGui.QPixmap("humpbackWhale.png"))
        self.AUS_humpW_2.setScaledContents(True)
        self.AUS_humpW_2.setObjectName("AUS_humpW_2")
        self.AF_headS = QtWidgets.QLabel(self.centralwidget)
        self.AF_headS.setGeometry(QtCore.QRect(1270, 550, 71, 41))
        self.AF_headS.setStyleSheet("background-color: rgb(207, 233, 250);")
        self.AF_headS.setText("")
        self.AF_headS.setPixmap(QtGui.QPixmap("HheadShark.png"))
        self.AF_headS.setScaledContents(True)
        self.AF_headS.setObjectName("AF_headS")
        self.AF_headS_3 = QtWidgets.QLabel(self.centralwidget)
        self.AF_headS_3.setGeometry(QtCore.QRect(560, 350, 71, 41))
        self.AF_headS_3.setStyleSheet("background-color: rgb(207, 233, 250);")
        self.AF_headS_3.setText("")
        self.AF_headS_3.setPixmap(QtGui.QPixmap("HheadShark.png"))
        self.AF_headS_3.setScaledContents(True)
        self.AF_headS_3.setObjectName("AF_headS_3")
        self.AF_headS_2 = QtWidgets.QLabel(self.centralwidget)
        self.AF_headS_2.setGeometry(QtCore.QRect(240, 320, 71, 41))
        self.AF_headS_2.setStyleSheet("background-color: rgb(207, 233, 250);")
        self.AF_headS_2.setText("")
        self.AF_headS_2.setPixmap(QtGui.QPixmap("HheadShark.png"))
        self.AF_headS_2.setScaledContents(True)
        self.AF_headS_2.setObjectName("AF_headS_2")
        self.AF_greatwS_3 = QtWidgets.QLabel(self.centralwidget)
        self.AF_greatwS_3.setGeometry(QtCore.QRect(700, 610, 71, 31))
        self.AF_greatwS_3.setStyleSheet("background-color: rgb(200, 235, 255);")
        self.AF_greatwS_3.setText("")
        self.AF_greatwS_3.setPixmap(QtGui.QPixmap("GreatWshark.png"))
        self.AF_greatwS_3.setScaledContents(True)
        self.AF_greatwS_3.setObjectName("AF_greatwS_3")
        self.AF_blueW = QtWidgets.QLabel(self.centralwidget)
        self.AF_blueW.setGeometry(QtCore.QRect(1290, 330, 51, 31))
        self.AF_blueW.setStyleSheet("\n""background-color: rgb(200, 235, 255);")
        self.AF_blueW.setText("")
        self.AF_blueW.setPixmap(QtGui.QPixmap("Bluewhale.png"))
        self.AF_blueW.setScaledContents(True)
        self.AF_blueW.setObjectName("AF_blueW")
        self.AS_SpermW_2 = QtWidgets.QLabel(self.centralwidget)
        self.AS_SpermW_2.setGeometry(QtCore.QRect(1250, 570, 61, 51))
        self.AS_SpermW_2.setStyleSheet("background-color: rgb(218, 240, 253);")
        self.AS_SpermW_2.setText("")
        self.AS_SpermW_2.setPixmap(QtGui.QPixmap("spermWhale.png"))
        self.AS_SpermW_2.setScaledContents(True)
        self.AS_SpermW_2.setObjectName("AS_SpermW_2")
        self.instructions = QtWidgets.QLabel(self.centralwidget)
        self.instructions.setGeometry(QtCore.QRect(350, 40, 701, 20))
        self.instructions.setStyleSheet("background-color: rgb(246, 208, 255);\n"
                                        "font: 14pt \"Palatino Linotype\";")
        self.instructions.setObjectName("instructions")
        self.predict = QtWidgets.QPushButton(self.centralwidget)
        self.predict.setGeometry(QtCore.QRect(1060, 30, 111, 41))
        self.predict.setStyleSheet("background-color: rgb(77, 98, 175);\n"
                                   "font: 14pt \"Palatino Linotype\";\n"
                                   "\n"
                                   "color: rgb(255, 255, 255);")
        self.predict.setObjectName("predict")

        self.location_now = QtWidgets.QLabel(self.centralwidget)
        self.location_now.setGeometry(QtCore.QRect(480, 330, 41, 41))
        self.location_now.setStyleSheet("background-color: rgb(200, 234, 251);")
        self.location_now.setText("")
        self.location_now.setPixmap(QtGui.QPixmap("cross.png"))
        self.location_now.setScaledContents(True)
        self.location_now.setObjectName("location_now")
        self.SA_dot = QtWidgets.QLabel(self.centralwidget)
        self.SA_dot.setGeometry(QtCore.QRect(200, 161, 101, 51))
        self.SA_dot.setStyleSheet("background-color: rgb(200, 235, 255);")
        self.SA_dot.setText("")
        self.SA_dot.setScaledContents(False)
        self.SA_dot.setObjectName("SA_dot")
        self.month = QtWidgets.QPushButton(self.centralwidget)
        self.month.setGeometry(QtCore.QRect(210, 20, 131, 41))
        self.month.setStyleSheet("background-color: rgb(77, 98, 175);\n" "font: 14pt \"Palatino Linotype\";\n"
                                      "\n"
                                      "color: rgb(255, 255, 255);")
        self.month.setObjectName("month")
        self.month_menu = QtWidgets.QWidget(self.centralwidget)
        self.month_menu.setGeometry(QtCore.QRect(230, 70, 111, 371))
        self.month_menu.setStyleSheet("background-color: rgb(77, 98, 175);")
        self.month_menu.setObjectName("month_menu")
        self.jan = QtWidgets.QPushButton(self.month_menu)
        self.jan.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.jan.setStyleSheet("color: rgb(77, 98, 175);\n"
                               "font: 8pt \"Palatino Linotype\";\n"
                               "\n"
                               "background-color: rgb(255, 255, 255);\n"
                               "")
        self.jan.setObjectName("jan")
        self.feb = QtWidgets.QPushButton(self.month_menu)
        self.feb.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.feb.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                               "color: rgb(77, 98, 175);")
        self.feb.setObjectName("feb")
        self.march = QtWidgets.QPushButton(self.month_menu)
        self.march.setGeometry(QtCore.QRect(10, 70, 91, 23))
        self.march.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "color: rgb(77, 98, 175);\n"
                                 "")
        self.march.setObjectName("march")
        self.april = QtWidgets.QPushButton(self.month_menu)
        self.april.setGeometry(QtCore.QRect(10, 100, 91, 23))
        self.april.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "color: rgb(77, 98, 175);")
        self.april.setObjectName("april")
        self.may = QtWidgets.QPushButton(self.month_menu)
        self.may.setGeometry(QtCore.QRect(10, 130, 91, 23))
        self.may.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                               "color: rgb(77, 98, 175);")
        self.may.setObjectName("may")
        self.june = QtWidgets.QPushButton(self.month_menu)
        self.june.setGeometry(QtCore.QRect(10, 160, 91, 23))
        self.june.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                "color: rgb(77, 98, 175);")
        self.june.setObjectName("june")
        self.july = QtWidgets.QPushButton(self.month_menu)
        self.july.setGeometry(QtCore.QRect(10, 190, 91, 23))
        self.july.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                "color: rgb(77, 98, 175);")
        self.july.setObjectName("july")
        self.aug = QtWidgets.QPushButton(self.month_menu)
        self.aug.setGeometry(QtCore.QRect(10, 220, 91, 23))
        self.aug.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                               "color: rgb(77, 98, 175);")
        self.aug.setObjectName("aug")
        self.sep = QtWidgets.QPushButton(self.month_menu)
        self.sep.setGeometry(QtCore.QRect(10, 250, 91, 23))
        self.sep.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                               "color: rgb(77, 98, 175);")
        self.sep.setObjectName("sep")
        self.oct = QtWidgets.QPushButton(self.month_menu)
        self.oct.setGeometry(QtCore.QRect(10, 280, 91, 23))
        self.oct.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                               "color: rgb(77, 98, 175);")
        self.oct.setObjectName("oct")
        self.nov = QtWidgets.QPushButton(self.month_menu)
        self.nov.setGeometry(QtCore.QRect(10, 310, 91, 23))
        self.nov.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                               "color: rgb(77, 98, 175);")
        self.nov.setObjectName("nov")
        self.dec = QtWidgets.QPushButton(self.month_menu)
        self.dec.setGeometry(QtCore.QRect(10, 340, 91, 23))
        self.dec.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                               "color: rgb(77, 98, 175);")
        self.dec.setObjectName("dec")
        self.month.raise_()
        self.month.hide()
        self.month_menu.raise_()

        self.predict.hide()
        self.predict.raise_()
        self.instructions.hide()
        self.imageWorld.raise_()
        self.heading.raise_()
        self.menu.raise_()
        self.zoom.raise_()
        self.zoomMenu.raise_()
        self.Main_blueW.raise_()
        self.World_blueW_2.raise_()
        self.World_blueW_3.raise_()
        self.Main_Hhead.raise_()
        self.World_Hhead_3.raise_()
        self.World_Hhead_2.raise_()
        self.World_SpermW_2.raise_()
        self.Main_SpermW.raise_()
        self.Main_monkSeal.raise_()
        self.Main_furSeal.raise_()
        self.World_hump_2.raise_()
        self.Main_hump.raise_()
        self.Main_greatW.raise_()
        self.World_greatW_3.raise_()
        self.World_greatW_2.raise_()
        self.NA_blueW.raise_()
        self.NA_blueW_3.raise_()
        self.NA_blueW_4.raise_()
        self.NA_SpermW.raise_()
        self.Main_finw.raise_()
        self.NA_finW.raise_()
        self.NA_humpW.raise_()
        self.NA_greatwS.raise_()
        self.SA_greatwS.raise_()
        self.SA_spermW.raise_()
        self.AS_SpermW.raise_()
        self.AS_greatwS_2.raise_()
        self.AS_headS.raise_()
        self.AS_headS_2.raise_()
        self.AUS_headS.raise_()
        self.AUS_greatwS.raise_()
        self.AUS_greatwS_2.raise_()
        self.AUS_SpermW.raise_()
        self.AUS_SpermW_2.raise_()
        self.AUS_humpW.raise_()
        self.AUS_humpW_2.raise_()
        self.AF_headS.raise_()
        self.AF_headS_3.raise_()
        self.AF_headS_2.raise_()
        self.AF_greatwS_3.raise_()
        self.AF_blueW.raise_()
        self.AS_SpermW_2.raise_()
        self.SA_dot.raise_()
        self.SA_dot.hide()
        self.key.hide()
        self.key.raise_()
        self.key_cross.hide()
        self.key_cross.raise_()
        self.location_now.hide()
        self.location_now.raise_()
        self.instructions.raise_()
        mainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1355, 21))
        self.menubar.setObjectName("menubar")
        mainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainMenu)
        self.statusbar.setObjectName("statusbar")
        mainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)
        self.world.clicked.connect(self.show_world)
        self.northA.clicked.connect(self.show_north)  # when northA is clicked it calls subroutine to show image
        self.southA.clicked.connect(self.show_south)  # when southA is clicked it calls show_south to display image
        self.zoom.clicked.connect(self.show_option)  # when zoom options is clicked a widget for options is shown
        self.asia.clicked.connect(self.show_asia)  # connect asia button to subroutine to display image
        self.australia.clicked.connect(self.show_aus)  # connect australia button to subroutine to display image
        self.africa.clicked.connect(self.show_africa)  # connect africa button to subroutine to display image
        self.Main_monkSeal.clicked.connect(self.Show_monkInfo)
        self.Main_blueW.clicked.connect(self.show_blueInfo)
        self.World_blueW_2.clicked.connect(self.show_blueInfo)
        self.World_blueW_3.clicked.connect(self.show_blueInfo)
        self.Main_finw.clicked.connect(self.show_finInfo)
        self.Main_furSeal.clicked.connect(self.show_furInfo)
        self.Main_greatW.clicked.connect(self.show_greatInfo)
        self.World_greatW_2.clicked.connect(self.show_greatInfo)
        self.World_greatW_3.clicked.connect(self.show_greatInfo)
        self.Main_Hhead.clicked.connect(self.show_hammerInfo)
        self.World_Hhead_2.clicked.connect(self.show_hammerInfo)
        self.World_Hhead_3.clicked.connect(self.show_hammerInfo)
        self.Main_hump.clicked.connect(self.show_humpInfo)
        self.World_hump_2.clicked.connect(self.show_humpInfo)
        self.Main_SpermW.clicked.connect(self.show_spermWInfo)
        self.World_SpermW_2.clicked.connect(self.show_spermWInfo)
        self.Prediction.clicked.connect(self.show_predictMenu)
        self.bw.clicked.connect(self.show_predictionBW)
        self.predict.clicked.connect(self.movement)
        self.close.clicked.connect(self.close_predict)
        self.hb.clicked.connect(self.show_predictionHB)
        self.month.clicked.connect(self.show_monthMenu)
        self.feb.clicked.connect(self.feb_location)
        self.jan.clicked.connect(self.jan_location)
        self.march.clicked.connect(self.march_location)
        self.april.clicked.connect(self.april_location)
        self.may.clicked.connect(self.may_location)
        self.june.clicked.connect(self.june_location)
        self.july.clicked.connect(self.july_location)
        self.aug.clicked.connect(self.aug_location)
        self.sep.clicked.connect(self.sep_location)
        self.oct.clicked.connect(self.oct_location)
        self.nov.clicked.connect(self.nov_location)
        self.dec.clicked.connect(self.dec_location)

        self.month_menu.hide()
        self.month_menu.hidden = True
        self.zoomMenu.hide()  # hide widget
        self.zoomMenu.hidden = True  # set zoom menu to be hidden
        self.Predict_menu.hide()
        self.Predict_menu.hidden = True
    # subroutine for when world button is selected (resets map back to original overview of map)
        self.NA_blueW.hide()  # setting all icons not on main world map to hidden
        self.NA_blueW_3.hide()
        self.NA_blueW_4.hide()
        self.NA_SpermW.hide()
        self.NA_finW.hide()
        self.NA_humpW.hide()
        self.NA_greatwS.hide()
        self.SA_greatwS.hide()
        self.SA_spermW.hide()
        self.AS_SpermW.hide()
        self.AS_greatwS.hide()
        self.AS_greatwS_2.hide()
        self.AS_headS.hide()
        self.AS_headS_2.hide()
        self.AUS_headS.hide()
        self.AUS_greatwS.hide()
        self.AUS_greatwS_2.hide()
        self.AUS_SpermW.hide()
        self.AUS_SpermW_2.hide()
        self.AUS_humpW.hide()
        self.AUS_humpW_2.hide()
        self.AF_headS.hide()
        self.AF_headS_3.hide()
        self.AF_headS_2.hide()
        self.AF_greatwS_3.hide()
        self.AF_blueW.hide()
        self.AS_SpermW_2.hide()
        self.SA_dot.hide()

    def show_world(self):

        self.imageWorld.setPixmap(QtGui.QPixmap("world_map.png"))  # map from files called and displayed in label
        self.World_blueW_2.show()
        self.World_blueW_3.show()
        self.World_Hhead_3.show()
        self.World_Hhead_2.show()
        self.World_SpermW_2.show()
        self.World_hump_2.show()
        self.World_greatW_3.show()
        self.World_greatW_2.show()
        self.AUS_humpW_2.hide()
        self.AUS_headS.hide()
        self.AUS_SpermW.hide()
        self.AUS_SpermW_2.hide()
        self.AUS_humpW.hide()
        self.AUS_greatwS.hide()
        self.AUS_greatwS_2.hide()
        self.AF_headS.hide()
        self.AF_headS_3.hide()
        self.AF_headS_2.hide()
        self.AF_greatwS_3.hide()
        self.AF_blueW.hide()
        self.AS_SpermW.hide()
        self.AS_headS.hide()
        self.AS_headS_2.hide()
        self.AS_greatwS_2.hide()
        self.AS_greatwS.hide()
        self.AS_SpermW_2.hide()
        self.NA_blueW.hide()
        self.NA_blueW_3.hide()
        self.NA_blueW_4.hide()
        self.NA_SpermW.hide()
        self.NA_finW.hide()
        self.NA_humpW.hide()
        self.NA_greatwS.hide()
        self.SA_greatwS.hide()
        self.SA_spermW.hide()
        self.SA_dot.hide()
        self.Main_hump.show()
        self.Main_furSeal.show()
        self.Main_monkSeal.show()
        self.Main_finw.show()
        self.Main_blueW.show()

        self.Main_Hhead.show()
        self.Main_SpermW.show()
        self.Main_greatW.show()

        self.Main_finw.setGeometry(QtCore.QRect(500, 160, 61, 41))
        self.Main_hump.setGeometry(QtCore.QRect(860, 280, 61, 41))
        self.Main_Hhead.setGeometry(QtCore.QRect(410, 260, 61, 41))
        self.Main_blueW.setGeometry(QtCore.QRect(360, 410, 61, 41))
        self.Main_SpermW.setGeometry(QtCore.QRect(540, 460, 61, 41))
        self.Main_furSeal.setGeometry(QtCore.QRect(1161, 140, 61, 41))
        self.Main_greatW.setGeometry(QtCore.QRect(1180, 400, 61, 41))
        self.Main_monkSeal.setGeometry(QtCore.QRect(200, 260, 51, 61))

    def show_north(self):
        self.imageWorld.setPixmap(QtGui.QPixmap("North_america.svg"))
        self.World_blueW_2.hide()
        self.World_blueW_3.hide()
        self.World_Hhead_3.hide()
        self.World_Hhead_2.hide()
        self.World_SpermW_2.hide()
        self.World_hump_2.hide()
        self.World_greatW_3.hide()
        self.World_greatW_2.hide()
        self.NA_blueW.hide()
        self.NA_blueW_3.hide()
        self.NA_blueW_4.hide()
        self.NA_SpermW.hide()
        self.NA_finW.hide()
        self.NA_humpW.hide()
        self.SA_spermW.hide()
        self.SA_greatwS.hide()
        self.SA_dot.hide()
        self.AS_SpermW.hide()
        self.AS_greatwS.hide()
        self.AS_greatwS_2.hide()
        self.AS_headS.hide()
        self.AS_headS_2.hide()
        self.AUS_headS.hide()
        self.AUS_greatwS.hide()
        self.AUS_greatwS_2.hide()
        self.AUS_SpermW.hide()
        self.AUS_SpermW_2.hide()
        self.AUS_humpW.hide()
        self.AUS_humpW_2.hide()
        self.AF_headS.hide()
        self.AF_headS_3.hide()
        self.AF_headS_2.hide()
        self.AF_greatwS_3.hide()
        self.AF_blueW.hide()
        self.AS_SpermW_2.hide()
        self.Main_monkSeal.hide()
        self.Main_furSeal.show()
        self.Main_blueW.show()
        self.Main_finw.show()
        self.Main_hump.show()

        self.Main_Hhead.show()
        self.Main_SpermW.show()
        self.Main_greatW.show()
        self.NA_blueW.show()
        self.NA_blueW_3.show()
        self.NA_blueW_4.show()
        self.NA_SpermW.show()
        self.NA_finW.show()
        self.NA_humpW.show()

        self.Main_finw.setGeometry(QtCore.QRect(1040, 200, 61, 41))
        self.Main_hump.setGeometry(QtCore.QRect(650, 540, 61, 41))
        self.Main_Hhead.setGeometry(QtCore.QRect(1020, 540, 61, 41))
        self.Main_blueW.setGeometry(QtCore.QRect(440, 230, 61, 41))
        self.Main_SpermW.setGeometry(QtCore.QRect(1050, 380, 61, 41))
        self.Main_furSeal.setGeometry(QtCore.QRect(470, 320, 61, 41))
        self.Main_greatW.setGeometry(QtCore.QRect(570, 510, 61, 41))

    def show_south(self):
        self.imageWorld.setPixmap(QtGui.QPixmap("South_America.svg"))  # map from files called and displayed in label
        self.World_blueW_2.hide()
        self.World_blueW_3.hide()
        self.World_Hhead_3.hide()
        self.World_Hhead_2.hide()
        self.World_SpermW_2.hide()
        self.World_hump_2.hide()
        self.World_greatW_3.hide()
        self.World_greatW_2.hide()
        self.NA_blueW.hide()
        self.NA_blueW_3.hide()
        self.NA_blueW_4.hide()
        self.NA_SpermW.hide()
        self.NA_finW.hide()
        self.NA_humpW.hide()
        self.AS_SpermW.hide()
        self.AS_greatwS.hide()
        self.AS_greatwS_2.hide()
        self.AS_headS.hide()
        self.AS_headS_2.hide()
        self.AUS_headS.hide()
        self.AUS_greatwS.hide()
        self.AUS_greatwS_2.hide()
        self.AUS_SpermW.hide()
        self.AUS_SpermW_2.hide()
        self.AUS_humpW.hide()
        self.AUS_humpW_2.hide()
        self.AF_headS.hide()
        self.AF_headS_3.hide()
        self.AF_headS_2.hide()
        self.AF_greatwS_3.hide()
        self.AF_blueW.hide()
        self.AS_SpermW_2.hide()
        self.Main_finw.hide()
        self.Main_furSeal.hide()
        self.SA_greatwS.show()
        self.SA_dot.show()
        self.Main_hump.show()
        self.Main_blueW.show()
        self.Main_monkSeal.show()

        self.Main_Hhead.show()
        self.Main_SpermW.show()
        self.Main_greatW.show()

        self.Main_monkSeal.setGeometry(QtCore.QRect(280, 210, 61, 41))
        self.Main_hump.setGeometry(QtCore.QRect(570, 240, 61, 41))
        self.Main_Hhead.setGeometry(QtCore.QRect(680, 110, 61, 41))
        self.Main_blueW.setGeometry(QtCore.QRect(720, 370, 61, 41))
        self.Main_SpermW.setGeometry(QtCore.QRect(1140, 410, 61, 41))
        self.Main_greatW.setGeometry(QtCore.QRect(600, 300, 61, 41))

    def show_asia(self):
        self.imageWorld.setPixmap(QtGui.QPixmap("Asia.png"))  # map of asia set using pixmap in main world label
        self.World_blueW_2.hide()
        self.World_blueW_3.hide()
        self.World_Hhead_3.hide()
        self.World_Hhead_2.hide()
        self.World_SpermW_2.hide()
        self.World_hump_2.hide()
        self.World_greatW_3.hide()
        self.World_greatW_2.hide()
        self.NA_blueW.hide()
        self.NA_blueW_3.hide()
        self.NA_blueW_4.hide()
        self.NA_SpermW.hide()
        self.NA_finW.hide()
        self.NA_humpW.hide()
        self.AUS_headS.hide()
        self.AUS_greatwS.hide()
        self.AUS_greatwS_2.hide()
        self.AUS_SpermW.hide()
        self.AUS_SpermW_2.hide()
        self.AUS_humpW.hide()
        self.AUS_humpW_2.hide()
        self.AF_headS.hide()
        self.AF_headS_3.hide()
        self.AF_headS_2.hide()
        self.AF_greatwS_3.hide()
        self.AF_blueW.hide()
        self.AS_SpermW_2.show()
        self.Main_finw.hide()
        self.Main_blueW.hide()
        self.Main_furSeal.hide()
        self.SA_greatwS.hide()
        self.SA_dot.hide()
        self.Main_monkSeal.hide()

        self.SA_spermW.hide()
        self.AS_SpermW.show()
        self.AS_greatwS.show()
        self.AS_greatwS_2.show()
        self.AS_headS.show()
        self.AS_headS_2.show()

        self.Main_Hhead.show()
        self.Main_SpermW.show()
        self.Main_greatW.show()
        self.Main_hump.show()
        self.Main_hump.setGeometry(QtCore.QRect(510, 390, 61, 41))
        self.Main_Hhead.setGeometry(QtCore.QRect(710, 420, 61, 41))
        self.Main_SpermW.setGeometry(QtCore.QRect(1130, 260, 61, 41))
        self.Main_greatW.setGeometry(QtCore.QRect(1070, 330, 61, 41))

    def show_aus(self):

        self.imageWorld.setPixmap(QtGui.QPixmap("australia.svg"))  # map of australia shown in label
        self.World_blueW_2.hide()
        self.World_blueW_3.hide()
        self.World_Hhead_3.hide()
        self.World_Hhead_2.hide()
        self.World_SpermW_2.hide()
        self.World_hump_2.hide()
        self.World_greatW_3.hide()
        self.World_greatW_2.hide()
        self.NA_blueW.hide()
        self.NA_blueW_3.hide()
        self.NA_blueW_4.hide()
        self.NA_SpermW.hide()
        self.NA_finW.hide()
        self.NA_humpW.hide()
        self.AF_headS.hide()
        self.AF_headS_3.hide()
        self.AF_headS_2.hide()
        self.AF_greatwS_3.hide()
        self.AF_blueW.hide()
        self.AS_SpermW_2.show()
        self.SA_greatwS.hide()
        self.SA_dot.hide()
        self.SA_spermW.hide()
        self.AS_SpermW_2.hide()

        self.AS_SpermW.hide()
        self.AS_greatwS.hide()
        self.AS_greatwS_2.hide()
        self.AS_headS.hide()
        self.AS_headS_2.hide()

        self.AUS_headS.show()
        self.AUS_greatwS.show()
        self.AUS_greatwS_2.show()
        self.AUS_SpermW.show()
        self.AUS_SpermW_2.show()
        self.AUS_humpW.show()
        self.AUS_humpW_2.show()
        self.Main_finw.show()
        self.Main_furSeal.hide()
        self.Main_monkSeal.hide()
        self.Main_blueW.show()
        self.Main_hump.show()

        self.Main_Hhead.show()
        self.Main_SpermW.show()
        self.Main_greatW.show()
        self.Main_hump.setGeometry(QtCore.QRect(650, 350, 61, 41))
        self.Main_Hhead.setGeometry(QtCore.QRect(1020, 540, 61, 41))
        self.Main_SpermW.setGeometry(QtCore.QRect(950, 270, 61, 41))
        self.Main_greatW.setGeometry(QtCore.QRect(420, 450, 61, 41))
        self.Main_finw.setGeometry(QtCore.QRect(300, 466, 61, 41))
        self.Main_blueW.setGeometry(QtCore.QRect(280, 390, 61, 41))

    def show_africa(self):
        self.imageWorld.setPixmap(QtGui.QPixmap("africa1.jpg"))  # map of africa shown in label

        self.World_blueW_2.hide()
        self.World_blueW_3.hide()
        self.World_Hhead_3.hide()
        self.World_Hhead_2.hide()
        self.World_SpermW_2.hide()
        self.World_hump_2.hide()
        self.World_greatW_3.hide()
        self.World_greatW_2.hide()
        self.NA_blueW.hide()
        self.NA_blueW_3.hide()
        self.NA_blueW_4.hide()
        self.NA_SpermW.hide()
        self.NA_finW.hide()
        self.NA_humpW.hide()
        self.AS_SpermW_2.hide()
        self.SA_greatwS.hide()
        self.SA_dot.hide()
        self.SA_spermW.hide()
        self.AS_SpermW.hide()
        self.AS_greatwS.hide()
        self.AS_greatwS_2.hide()
        self.AS_headS.hide()
        self.AS_headS_2.hide()
        self.AUS_headS.hide()
        self.AUS_greatwS.hide()
        self.AUS_greatwS_2.hide()
        self.AUS_SpermW.hide()
        self.AUS_SpermW_2.hide()
        self.AUS_humpW.hide()
        self.AUS_humpW_2.hide()

        self.AF_headS.show()
        self.AF_headS_3.show()
        self.AF_headS_2.show()
        self.AF_greatwS_3.show()
        self.AF_blueW.show()

        self.Main_blueW.show()
        self.Main_finw.show()
        self.Main_finw.show()
        self.Main_furSeal.hide()
        self.Main_monkSeal.hide()
        self.Main_hump.hide()

        self.Main_Hhead.show()
        self.Main_SpermW.show()
        self.Main_greatW.show()
        self.Main_Hhead.setGeometry(QtCore.QRect(1240, 430, 61, 41))
        self.Main_SpermW.setGeometry(QtCore.QRect(640, 440, 61, 41))
        self.Main_greatW.setGeometry(QtCore.QRect(1120, 570, 61, 41))
        self.Main_finw.setGeometry(QtCore.QRect(330, 70, 61, 41))
        self.Main_blueW.setGeometry(QtCore.QRect(1120, 570, 61, 41))

    # subroutine to show menu options
    def show_option(self):
        if self.zoomMenu.hidden:  # checks whether it is shown or hidden
            self.zoomMenu.show()  # shows the zoom menu
            self.zoomMenu.hidden = False  # sets hidden variable to false
        else:
            self.zoomMenu.hide()  # hides zoom menu as if it is not hidden it must be shown
            self.zoomMenu.hidden = True  # sets hidden varibale to true

    def Show_monkInfo(self):
        self.window = QtWidgets.QDialog()
        self.ui = Information()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_blueInfo(self):
        self.window = QtWidgets.QDialog()
        self.ui = Info_BW()
        self.ui.setupUi(self.window)
        self.window.show()


    def show_finInfo(self):
        self.window = QtWidgets.QDialog()
        self.ui = Info_fw()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_furInfo(self):
        self.window = QtWidgets.QDialog()
        self.ui = Info_fur()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_greatInfo(self):
        self.window = QtWidgets.QDialog()
        self.ui = Info_GWS()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_hammerInfo(self):
        self.window = QtWidgets.QDialog()
        self.ui = Info_HH()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_humpInfo(self):
        self.window = QtWidgets.QDialog()
        self.ui = Info_hump()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_spermWInfo(self):
        self.window = QtWidgets.QDialog()
        self.ui = Info_sw()
        self.ui.setupUi(self.window)
        self.window.show()


    current_month = datetime.now()
    current_month = current_month.strftime("%m")
    x = 0
    y = 0

    def hide_all(self):
        self.World_blueW_2.hide()
        self.World_blueW_3.hide()
        self.World_Hhead_3.hide()
        self.World_Hhead_2.hide()
        self.World_SpermW_2.hide()
        self.World_hump_2.hide()
        self.World_greatW_3.hide()
        self.World_greatW_2.hide()
        self.AUS_humpW_2.hide()
        self.AUS_headS.hide()
        self.AUS_SpermW.hide()
        self.AUS_SpermW_2.hide()
        self.AUS_humpW.hide()
        self.AUS_greatwS.hide()
        self.AUS_greatwS_2.hide()
        self.AF_headS.hide()
        self.AF_headS_3.hide()
        self.AF_headS_2.hide()
        self.AF_greatwS_3.hide()
        self.AF_blueW.hide()
        self.AS_SpermW.hide()
        self.AS_headS.hide()
        self.AS_headS_2.hide()
        self.AS_greatwS_2.hide()
        self.AS_greatwS.hide()
        self.AS_SpermW_2.hide()
        self.NA_blueW.hide()
        self.NA_blueW_3.hide()
        self.NA_blueW_4.hide()
        self.NA_SpermW.hide()
        self.NA_finW.hide()
        self.NA_humpW.hide()
        self.NA_greatwS.hide()
        self.SA_greatwS.hide()
        self.SA_spermW.hide()
        self.SA_dot.hide()
        self.Main_hump.hide()
        self.Main_furSeal.hide()
        self.Main_monkSeal.hide()
        self.Main_finw.hide()
        self.Main_blueW.show()
        self.Main_Hhead.hide()
        self.Main_SpermW.hide()
        self.Main_greatW.hide()
        self.zoom.hide()
        self.zoomMenu.hide()

    movement_BW = False
    movement_HB = False
    def show_predictMenu(self):

        if self.Predict_menu.hidden:  # checks whether it is shown or hidden
            self.Predict_menu.show()  # shows the predict menu
            self.Predict_menu.hidden = False  # sets hidden variable to false
        else:
            self.Predict_menu.hide()  # hides zoom menu as if it is not hidden it must be shown
            self.Predict_menu.hidden = True  # sets hidden varibale to true

    def show_monthMenu(self):

        if self.month_menu.hidden:  # checks whether it is shown or hidden
            self.month_menu.show()  # shows the predict menu
            self.month_menu.hidden = False  # sets hidden variable to false
        else:
            self.month_menu.hide()  # hides zoom menu as if it is not hidden it must be shown
            self.month_menu.hidden = True  # sets hidden varibale to true

    def show_predictionHB(self):
        self.movement_HB = True
        self.movement_BW = False
        self.imageWorld.setPixmap(QtGui.QPixmap("HumpbackMap.png"))
        self.month.show()
        self.month_menu.raise_()
        self.hide_all()
        self.instructions.show()
        self.predict.show()
        self.key.show()
        self.location_now.show()
        self.key_cross.show()
        self.Main_hump.show()
        self.Main_hump.raise_()
        self.Main_blueW.hide()

        self.cross_HB()

    def show_predictionBW(self):
        self.imageWorld.setPixmap(QtGui.QPixmap("North_america.svg"))
        self.hide_all()
        self.instructions.show()
        self.predict.show()
        self.Main_blueW.show()
        self.key.show()
        self.key_cross.show()
        self.location_now.show()
        self.Main_blueW.raise_()
        self.cross_BW()
        self.month.show()
        self.month_menu.raise_()
        self.movement_BW = True
        self.movement_HB = False

    def feb_location(self) :
        self.current_month = "02"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(760, 580, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(760, 580, 61, 41))
            self.x = 760
            self.y = 580

        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(600, 480, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(600, 480, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 600
            self.y = 480

    def jan_location(self):
        self.current_month = "01"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(890, 590, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(890, 590, 61, 41))
            self.x = 890
            self.y = 590

        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(510, 470, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(510, 470, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 510
            self.y = 470

    def march_location(self):
        self.current_month = "03"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(640, 540, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(640, 540, 61, 41))
            self.x = 640
            self.y = 540

        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(690, 420, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(690, 420, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 690
            self.y = 420


    def april_location(self):
        self.current_month = "04"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(520, 460, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(520, 460, 61, 41))
            self.x = 520
            self.y = 460

        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(680, 350, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(680, 350, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 870
            self.y = 350


    def may_location(self):
        self.current_month = "05"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(470, 410, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(470, 410, 61, 41))
            self.x = 470
            self.y = 410
        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(900, 320, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(900, 320, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 900
            self.y = 320


    def june_location(self):
        self.current_month = "06"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(460, 350, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(460, 350, 61, 41))
            self.x = 460
            self.y = 350
        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(930, 290, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(930, 290, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 930
            self.y = 290

    def july_location(self):
        self.current_month = "07"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(430, 230, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(430, 230, 61, 41))
            self.x = 430
            self.y = 230

        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(960, 220, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(960, 220, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 960
            self.y = 220


    def aug_location(self):
        self.current_month = "08"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(440, 280, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(440, 280, 61, 41))
            self.x = 440
            self.y = 280

        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(940, 200, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(940, 200, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 940
            self.y = 200


    def sep_location(self):
        self.current_month = "09"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(420, 340, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(420, 340, 61, 41))
            self.x = 420
            self.y = 340

        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(960, 280, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(960, 280, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 960
            self.y = 280


    def oct_location(self):
        self.current_month = "10"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(440, 420, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(440, 420, 61, 41))
            self.x = 440
            self.y = 420

        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(890, 330, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(890, 330, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 890
            self.y = 330


    def nov_location(self):
        self.current_month = "11"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(570, 510, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(570, 510, 61, 41))
            self.x = 570
            self.y = 510
        elif self.movement_HB == True:
            self.location_now.setGeometry(QtCore.QRect(840, 370, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(840, 370, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 840
            self.y = 370

    def dec_location(self):
        self.current_month = "12"
        if self.movement_BW == True:
            self.location_now.setGeometry(QtCore.QRect(840, 580, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(840, 580, 61, 41))
            self.x = 840
            self.y = 580
        elif self.movement_HB:
            self.location_now.setGeometry(QtCore.QRect(760, 400, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(760, 400, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 760
            self.y = 400

    def cross_BW(self):
        if self.current_month == "04":
            self.location_now.setGeometry(QtCore.QRect(520, 460, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(520, 460, 61, 41))
            self.x = 520
            self.y = 460

        elif self.current_month == "01":
            self.location_now.setGeometry(QtCore.QRect(890, 590, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(890, 590, 61, 41))
            self.x = 890
            self.y = 590

        elif self.current_month == "02":
            self.location_now.setGeometry(QtCore.QRect(760, 580, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(760, 580, 61, 41))
            self.x = 760
            self.y = 580

        elif self.current_month == "03":
            self.location_now.setGeometry(QtCore.QRect(640, 540, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(640, 540, 61, 41))
            self.x = 640
            self.y = 540

        elif self.current_month == "05":
            self.location_now.setGeometry(QtCore.QRect(470, 410, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(470, 410, 61, 41))
            self.x = 470
            self.y = 410

        elif self.current_month == "06":
            self.location_now.setGeometry(QtCore.QRect(460, 350, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(460, 350, 61, 41))
            self.x = 460
            self.y = 350

        elif self.current_month == "07":
            self.location_now.setGeometry(QtCore.QRect(430, 230, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(430, 230, 61, 41))
            self.x = 430
            self.y = 230

        elif self.current_month == "08":
            self.location_now.setGeometry(QtCore.QRect(440, 280, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(440, 280, 61, 41))
            self.x = 440
            self.y = 280

        elif self.current_month == "09":
            self.location_now.setGeometry(QtCore.QRect(420, 340, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(420, 340, 61, 41))
            self.x = 420
            self.y = 340

        elif self.current_month == "10":
            self.location_now.setGeometry(QtCore.QRect(440, 420, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(440, 420, 61, 41))
            self.x = 440
            self.y = 420

        elif self.current_month == "11":
            self.location_now.setGeometry(QtCore.QRect(570, 510, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(570, 510, 61, 41))
            self.x = 570
            self.y = 510

        elif self.current_month == "12":
            self.location_now.setGeometry(QtCore.QRect(840, 580, 61, 41))
            self.Main_blueW.setGeometry(QtCore.QRect(840, 580, 61, 41))
            self.x = 840
            self.y = 580


    def cross_HB(self):
        if self.current_month == "01":
            self.location_now.setGeometry(QtCore.QRect(510, 470, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(510, 470, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 510
            self.y = 470

        elif self.current_month == "02":
            self.location_now.setGeometry(QtCore.QRect(600, 480, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(600, 480, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 600
            self.y = 480

        elif self.current_month == "03":
            self.location_now.setGeometry(QtCore.QRect(690, 420, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(690, 420, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 690
            self.y = 420

        elif self.current_month == "04":
            self.location_now.setGeometry(QtCore.QRect(680, 350, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(680, 350, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 870
            self.y = 350

        elif self.current_month == "05":
            self.location_now.setGeometry(QtCore.QRect(900, 320, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(900, 320, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 900
            self.y = 320

        elif self.current_month == "06":
            self.location_now.setGeometry(QtCore.QRect(930, 290, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(930, 290, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 930
            self.y = 290

        elif self.current_month == "07":
            self.location_now.setGeometry(QtCore.QRect(960, 220, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(960, 220, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 960
            self.y = 220

        elif self.current_month == "08":
            self.location_now.setGeometry(QtCore.QRect(940, 200, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(940, 200, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 940
            self.y = 200

        elif self.current_month == "09":
            self.location_now.setGeometry(QtCore.QRect(960, 280, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(960, 280, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 960
            self.y = 280

        elif self.current_month == "10":
            self.location_now.setGeometry(QtCore.QRect(890, 330, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(890, 330, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 890
            self.y = 330

        elif self.current_month == "11":
            self.location_now.setGeometry(QtCore.QRect(840, 370, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(840, 370, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 840
            self.y = 370

        elif self.current_month == "12":
            self.location_now.setGeometry(QtCore.QRect(760, 400, 41, 31))
            self.Main_hump.setGeometry(QtCore.QRect(760, 400, 41, 31))
            self.Main_hump.setIconSize(QtCore.QSize(40, 40))
            self.x = 760
            self.y = 400


    def close_predict(self):
        self.instructions.hide()
        self.predict.hide()
        self.zoom.show()
        self.key.hide()
        self.key_cross.hide()
        self.location_now.hide()
        self.month.hide()
        self.month_menu.hide()

    winter = ["12", "01", "02"]
    summer = ["06", "07", "08"]
    autumn = ["09", "10", "11"]
    spring = ["03", "04", "05"]
    summerX = 450
    summerY = 220
    winterX = 910
    winterY = 600

    def movement(self):
        if self.movement_BW == True :
            difference_x = 0
            difference_y = 0
            difference_x = self.winterX - self.summerX
            difference_y = self.winterY - self.summerY
            if self.current_month in self.summer:
                self.x = self.x + difference_x
                self.y = self.y + difference_y
                self.y = int(self.y)
                self.x = int(self.x)
                if 380 <= self.y <= 450:
                    self.x = 460
                    self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                elif self.y > 590:
                    self.y = 590
                    self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                else:
                    self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                if self.current_month == "06":
                    self.x = 460
                    self.y = 350
                elif self.current_month == "07":
                    self.x = 43
                    self.y = 230
                elif self.current_month == "08":
                    self.x = 440
                    self.y = 280

            elif self.current_month in self.winter:
                self.x = self.x - difference_x
                self.y = self.y - difference_y
                self.y = int(self.y)
                self.x = int(self.x)
                if 380 <= self.y <= 450:
                    self.x = 460
                    self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                elif self.y > 590:
                    self.y = 590
                    self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))

                else:
                    self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))

                if self.current_month == "12":
                    self.x = 840
                    self.y = 580
                elif self.current_month == "01":
                    self.x = 890
                    self.y = 590
                elif self.current_month == "02":
                    self.x = 760
                    self.y = 580

            elif self.current_month in self.spring:
                if self.current_month == "03":
                    difference_x = difference_x / 2
                    difference_y = difference_y / 2
                    self.x = self.x - difference_x
                    self.y = self.y - difference_y
                    self.y = int(self.y)
                    self.x = int(self.x)
                    if 380 <= self.y <= 450:
                        self.x = 460
                        self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                        self.x = 640
                        self.y = 540
                    else:
                        self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                        self.x = 640
                        self.y = 540
                else:
                    difference_x = difference_x / 4
                    difference_y = difference_y / 4
                    self.y = int(self.y)
                    self.x = int(self.x)
                    if self.current_month == "04":
                        self.x = self.x - difference_x
                        self.y = self.y - difference_y
                        if 380 <= self.y <= 450:
                            self.x = 460
                            self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                            self.x = 520
                            self.y = 470

                        else:
                            self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                            self.x = 520
                            self.y = 470
                    else:
                        self.x = self.x + difference_x
                        self.y = self.y + difference_y
                        if 380 <= self.y <= 450:
                            self.x = 460
                            self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                            self.x = 470
                            self.y = 410
                        else:
                            self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                            self.x = 470
                            self.y = 410

            elif self.current_month in self.autumn:
                if self.current_month == "09":
                    difference_x = difference_x / 2
                    difference_y = difference_y / 2
                    self.x = self.x + difference_x
                    self.y = self.y + difference_y
                    self.y = int(self.y)
                    self.x = int(self.x)
                    if 380 <= self.y <= 450:
                        self.x = 460
                        self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                        self.x = 420
                        self.y = 340
                    else:
                        self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                        self.x = 420
                        self.y = 340
                else:
                    difference_x = difference_x / 4
                    difference_y = difference_y / 4
                    self.y = int(self.y)
                    self.x = int(self.x)
                    if self.current_month == "10":
                        self.x = self.x + difference_x
                        self.y = self.y + difference_y
                        if 380 <= self.y <= 450:
                            self.x = 460
                            self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                            self.current = 440
                            self.current = 420

                        else:
                            self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                            self.current = 440
                            self.current = 420

                    else:
                        self.x = self.x - difference_x
                        self.y = self.y - difference_y
                        if 380 <= self.y <= 450:
                            self.x = 460
                            self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                            self.x = 570
                            self.y = 510

                        else:
                            self.Main_blueW.setGeometry(QtCore.QRect(self.x, self.y, 61, 41))
                            self.x = 570
                            self.y = 510

        elif self.movement_HB == True :
            distance_x = 0
            distance_x = 940 - 520
            speed = 9.4
            six_month = 0
            six_month = 24 * 183
            distance_km = 0
            distance_km = speed * six_month
            distance_y = 0
            distance_y = distance_km * 0.00678
            if self.current_month in self.spring :
                distance_y = distance_y / 4
                distance_y = int(distance_y)
                if self.current_month == "03":
                    distance_x = distance_x / 2
                    self.y = self.y - distance_y
                    self.x = self.x + distance_x
                    self.y = int(self.y)
                    self.x = int(self.x)
                    if self.x >= 900 :
                        self.x = 920
                        self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))
                    else:
                        self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))
                elif self.current_month == "04":
                    distance_x = distance_x / 6
                    self.x = self.x + distance_x
                    self.y = self.y - distance_y
                    self.y = int(self.y)
                    self.x = int(self.x)
                    self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))
                elif self.current_month == "05" :
                    distance_x = distance_x / 6
                    self.x = self.x - distance_x
                    self.y = self.y + distance_y
                    self.y = int(self.y)
                    self.x = int(self.x)
                    self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31 ))

                if self.current_month == "03":
                    self.x = 690
                    self.y = 420

                elif self.current_month == "04":
                    self.x = 870
                    self.y = 350

                elif self.current_month == "05":
                    self.x = 900
                    self.y = 320


            elif self.current_month in self.autumn :
                distance_y = distance_y / 4
                distance_y = int(distance_y)
                if self.current_month == "09":
                    distance_x = distance_x / 2
                    self.y = int(self.y)
                    self.x = int(self.x)
                    self.y = self.y + distance_y
                    self.x = self.x - distance_x

                    if self.x >= 900 :
                        self.x = 920
                        self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))
                    else:
                        self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))
                elif self.current_month == "10":
                    distance_x = distance_x / 6
                    self.x = self.x - distance_x
                    self.y = self.y + distance_y
                    self.y = int(self.y)
                    self.x = int(self.x)
                    self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))
                elif self.current_month == "11" :
                    distance_x = distance_x / 6
                    self.x = self.x + distance_x
                    self.y = self.y - distance_y
                    self.y = int(self.y)
                    self.x = int(self.x)
                    self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31 ))

                if self.current_month == "09":
                    self.x = 960
                    self.y = 280

                elif self.current_month == "10":
                    self.x = 890
                    self.y = 330

                elif self.current_month == "11":
                    self.x = 840
                    self.y = 370

            elif self.current_month in self.summer :
                if self.current_month == "06":
                    distance_y = distance_y / 2
                    self.y = self.y + distance_y
                    distance_x = distance_x / 2
                    self.x = self.x - distance_x
                    self.y = int(self.y)
                    self.x = int(self.x)
                    self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))
                elif self.current_month == "07" or self.current_month == "08":
                    self.y = self.y + distance_y
                    self.x = self.x - distance_x
                    self.y = int(self.y)
                    self.x = int(self.x)
                    self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))

                if self.current_month == "06":
                    self.x = 930
                    self.y = 290

                elif self.current_month == "07":
                    self.x = 960
                    self.y = 220
                elif self.current_month == "08":
                    self.x = 940
                    self.y = 200

            elif self.current_month in self.winter:
                if self.current_month == "12":
                    distance_y = distance_y / 2
                    distance_y = int(distance_y)
                    self.y = self.y - distance_y
                    distance_x = distance_x / 2
                    self.x = self.x + distance_x
                    self.y = int(self.y)
                    self.x = int(self.x)
                    self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))

                elif self.current_month == "01" or self.current_month == "02":
                    self.y = self.y - distance_y
                    self.x = self.x + distance_x
                    self.y = int(self.y)
                    self.x = int(self.x)
                    self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))
                    if self.x < 950 or self.x <= 1050:
                        self.x = 960
                        self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))
                    else:
                        self.Main_hump.setGeometry(QtCore.QRect(self.x, self.y, 41, 31))

                if self.current_month == "12":
                    self.x = 760
                    self.y = 400
                elif self.current_month == "01":
                    self.x = 510
                    self.y = 470

                elif self.current_month == "02":
                    self.x = 600
                    self.y = 480















    def retranslateUi(self, mainMenu):
        _translate = QtCore.QCoreApplication.translate
        mainMenu.setWindowTitle(_translate("mainMenu", "MainWindow"))
        self.heading.setText(_translate("mainMenu", "Where are the Whales?"))
        self.searchBut.setText(_translate("mainMenu", "Search"))
        self.overlayBut.setText(_translate("mainMenu", "Overlays"))
        self.sightingBut.setText(_translate("mainMenu", "Sightings"))
        self.Prediction.setText(_translate("mainMenu", "Prediction"))
        self.bw.setText(_translate("mainMenu", "Blue Whale"))
        self.hb.setText(_translate("mainMenu", "Humpback whale"))
        self.close.setText(_translate("mainMenu", "Close"))
        self.key.setText(_translate("mainMenu",  "             : Current selected month"))
        self.zoom.setText(_translate("mainMenu", "Zoom in"))
        self.northA.setText(_translate("mainMenu", "North America"))
        self.southA.setText(_translate("mainMenu", "South America"))
        self.asia.setText(_translate("mainMenu", "Asia"))
        self.australia.setText(_translate("mainMenu", "Australia"))
        self.africa.setText(_translate("mainMenu", "Africa"))
        self.world.setText(_translate("mainMenu", "Zoom Out"))
        self.instructions.setText(_translate("mainMenu", "select predict to see future movement in six months from the current month selected"))
        self.predict.setText(_translate("mainMenu", "Predict"))
        self.predict.setText(_translate("mainMenu", "predict"))
        self.month.setText(_translate("mainMenu", "current month"))
        self.jan.setText(_translate("mainMenu", "January"))
        self.feb.setText(_translate("mainMenu", "February"))
        self.march.setText(_translate("mainMenu", "March"))
        self.april.setText(_translate("mainMenu", "April"))
        self.may.setText(_translate("mainMenu", "May"))
        self.june.setText(_translate("mainMenu", "June"))
        self.july.setText(_translate("mainMenu", "July"))
        self.aug.setText(_translate("mainMenu", "August"))
        self.sep.setText(_translate("mainMenu", "September"))
        self.oct.setText(_translate("mainMenu", "October"))
        self.nov.setText(_translate("mainMenu", "November"))
        self.dec.setText(_translate("mainMenu", "December"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainMenu = QtWidgets.QMainWindow()
    ui = Ui_mainMenu()
    ui.setupUi(mainMenu)
    mainMenu.show()
    sys.exit(app.exec_())
